
import { GoogleGenAI } from "@google/genai";

// The route is POST /api/generate-pokemon-card, but its function is to generate a Bonk Gang image from a prompt.
export async function POST(request: Request) {
  // 1. Check for API Key
  if (!process.env.GEMINI_API_KEY) {
    console.error("GEMINI_API_KEY environment variable is not set.");
    return new Response(
        JSON.stringify({ message: "The service is temporarily unavailable. Please try again later." }),
        { status: 503, headers: { 'Content-Type': 'application/json' } }
    );
  }

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

  // 2. Extract prompt from the request
  let characterDescription: string;
  try {
    const body = await request.json();
    if (!body.prompt) {
        throw new Error("No prompt provided in the request body.");
    }
    characterDescription = body.prompt;
  } catch (error) {
    const message = error instanceof Error ? error.message : "Invalid request body.";
    return new Response(JSON.stringify({ message }), { status: 400, headers: { 'Content-Type': 'application/json' } });
  }


  // 3. Run the AI generation logic
  try {
    const imageModel = 'imagen-3.0-generate-002';
    
    // Generate the new character artwork.
    const artworkPrompt = `Digital art, masterpiece, cartoon style.
    Create an anthropomorphic dog character in the 'Bonk Gang' style.
    The character MUST be holding a large wooden baseball bat.
    Its appearance, clothing, and personality should be based on this description: "${characterDescription}".
    Style: fun, expressive, full body shot, slightly mischievous, similar to modern animated shows.
    Background: a simple, vibrant solid color gradient.
    CRITICAL: NO text, letters, logos, or borders on the image. ONLY the character and background.`;

    const imageResponse = await ai.models.generateImages({
        model: imageModel,
        prompt: artworkPrompt,
        config: { 
            numberOfImages: 1,
            outputMimeType: 'image/jpeg',
            aspectRatio: '1:1',
        },
    });

    const base64ImageBytes = imageResponse.generatedImages?.[0]?.image?.imageBytes;

    if (base64ImageBytes) {
      const artworkUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
      
      return new Response(JSON.stringify({ artworkUrl }), {
          status: 200,
          headers: { 'Content-Type': 'application/json' }
      });

    } else {
        throw new Error("No artwork was generated by the API.");
    }
  } catch (error) {
    console.error("Error in Bonk Gang image generation process:", error);
    let message = "An unknown error occurred during generation.";
    if (error instanceof Error) {
        // Check for specific Google API key error
        if (error.message.includes("API_KEY_INVALID")) {
            message = "The configured API key is invalid. Please check the GEMINI_API_KEY environment variable on the server.";
        } else {
            message = `The API failed to process the request: ${error.message}`;
        }
    }
    return new Response(
        JSON.stringify({ message }),
        { status: 500, headers: { 'Content-Type': 'application/json' } }
    );
  }
}
