
import React from 'react';
import Link from 'next/link';
import Header from '@/components/Header';

export default function TermsPage() {
  return (
    <div className="min-h-screen text-white p-4 sm:p-6 lg:p-8 flex flex-col items-center">
      <div className="w-full max-w-4xl flex flex-col items-center">
        <Header />
        <main className="w-full mt-8 bg-zinc-900 border-2 border-amber-400 rounded-lg p-6 md:p-8 text-gray-300">
          <h2 className="text-2xl sm:text-3xl font-bold text-amber-400 mb-6 text-center">Terms of Service</h2>
          
          <div className="space-y-4 text-sm sm:text-base leading-relaxed">
            <p>Welcome to the LetsBonkGang Official prompt page! These terms and conditions outline the rules and regulations for the use of our website.</p>

            <h3 className="text-xl text-amber-300 pt-4">1. Acceptance of Terms</h3>
            <p>By accessing this website, we assume you accept these terms and conditions. Do not continue to use LetsBonkGang Official prompt page if you do not agree to all of the terms and conditions stated on this page.</p>

            <h3 className="text-xl text-amber-300 pt-4">2. User-Generated Content</h3>
            <p>Our service allows you to upload images ("User Content") to generate new artwork. You are solely responsible for the User Content you submit. You represent and warrant that you own or have the necessary licenses, rights, consents, and permissions to your User Content.</p>
            <p>By submitting User Content, you grant us a worldwide, non-exclusive, royalty-free, sublicensable, and transferable license to use, reproduce, distribute, prepare derivative works of, and display the User Content in connection with the service and our business.</p>

            <h3 className="text-xl text-amber-300 pt-4">3. Prohibited Conduct</h3>
            <p>You agree not to submit any User Content that is illegal, defamatory, obscene, pornographic, threatening, or otherwise objectionable. We reserve the right to remove any content that violates these terms without notice.</p>

            <h3 className="text-xl text-amber-300 pt-4">4. Intellectual Property</h3>
            <p>The artwork generated by our service is a derivative work. While you retain ownership of your original User Content, the generated artwork is owned by the LetsBonkGang Official prompt page. We grant you a personal, non-commercial license to download and share the generated artwork.</p>

            <h3 className="text-xl text-amber-300 pt-4">5. Disclaimer of Warranties</h3>
            <p>This service is provided "as is," without warranty of any kind. We do not warrant that the service will be uninterrupted, error-free, or that the results obtained will be accurate or reliable.</p>

            <h3 className="text-xl text-amber-300 pt-4">6. Limitation of Liability</h3>
            <p>In no event shall the LetsBonkGang Official prompt page team be liable for any direct, indirect, incidental, special, or consequential damages arising out of the use or inability to use our service.</p>

            <h3 className="text-xl text-amber-300 pt-4">7. Changes to Terms</h3>
            <p>We reserve the right to modify these terms at any time. We will notify users of any changes by posting the new terms on this page. Your continued use of the service after any such changes constitutes your acceptance of the new terms.</p>
          </div>

          <div className="text-center mt-8">
            <Link href="/" className="px-6 py-2 bg-amber-400 text-black font-bold rounded-md transition-all duration-200 ease-in-out border-2 border-black shadow-[3px_3px_0px_#000] enabled:hover:bg-amber-500 enabled:active:translate-y-1 enabled:active:translate-x-1 enabled:active:shadow-none">
              Back to Home
            </Link>
          </div>
        </main>
        <footer className="mt-12 text-center text-xs text-gray-400">
            <p>Powered by LetsBonkGang Official Team &copy; 2025</p>
        </footer>
      </div>
    </div>
  );
}